extensions:
  aem/cf-console-admin/1:
    $include: src/aem-cf-console-admin-1/ext.config.yaml

configManifest:
  - label: 'Slack webhook URL'
    input: 'text'
    mapToEnv: 'SLACK_WEBHOOK'

  - label: 'Slack channel'
    input: 'text'
    mapToEnv: 'SLACK_CHANNEL'

  - label: 'Slack OAuth token'
    input: 'text'
    mapToEnv: 'SLACK_OAUTH_TOKEN'
